CREATE TABLE IF NOT EXISTS user
(
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    passward VARCHAR(255) NOT NULL,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);