export const packetNames = {
  common: {
    position: 'common.Position',
    baseData: 'common.BaseData',
    towerData: 'common.TowerData',
    monsterData: 'common.MonsterData',
    initialGameState: 'common.InitialGameState',
    gameState: 'common.GameState',
    globalFailCode: 'common.GlobalFailCode',
  },
  request: {
    C2SRegisterRequest: 'request.C2SRegisterRequest',
    C2SLoginRequest: 'request.C2SLoginRequest',
    C2SMatchRequest: 'request.C2SMatchRequest',
    C2STowerPurchaseRequest: 'request.C2STowerPurchaseRequest',
    C2SSpawnMonsterRequest: 'request.C2SSpawnMonsterRequest',
    C2STowerAttackRequest: 'request.C2STowerAttackRequest',
    C2SMonsterAttackBaseRequest: 'request.C2SMonsterAttackBaseRequest',
    C2SGameEndRequest: 'request.C2SGameEndRequest',
    C2SMonsterDeathNotification: 'request.C2SMonsterDeathNotification',
  },
  response: {
    S2CRegisterResponse: 'response.S2CRegisterResponse',
    S2CLoginResponse: 'response.S2CLoginResponse',
    S2CMatchStartNotification: 'response.S2CMatchStartNotification',
    S2CStateSyncNotification: 'response.S2CStateSyncNotification',
    S2CTowerPurchaseResponse: 'response.S2CTowerPurchaseResponse',
    S2CAddEnemyTowerNotification: 'response.S2CAddEnemyTowerNotification',
    S2CSpawnMonsterResponse: 'response.S2CSpawnMonsterResponse',
    S2CSpawnEnemyMonsterNotification: 'response.S2CSpawnEnemyMonsterNotification',
    S2CEnemyTowerAttackNotification: 'response.S2CEnemyTowerAttackNotification',
    S2CUpdateBaseHPNotification: 'response.S2CUpdateBaseHPNotification',
    S2CGameOverNotification: 'response.S2CGameOverNotification',
    S2CEnemyMonsterDeathNotification: 'response.S2CEnemyMonsterDeathNotification',
  },
  gamePacket: {
    gamePacket: 'gamePacket.GamePacket',
  },
};
